backend:
  name: git-gateway
  branch: main
# publish_mode: editorial_workflow
media_folder: public/img
public_folder: img
collections:
  - name: 'navLink' # Used in routes, e.g., /admin/collections/project
    label: 'NavLink' # Used in the UI
    folder: '_posts/navLink' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Label', name: 'label', widget: 'string' }
      - { label: 'Href', name: 'href', widget: 'string' }
