backend:
  name: git-gateway
  branch: main
local_backend: true
media_folder: public/img
public_folder: img
collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Home'
        name: 'home'
        file: 'content/home.md'
        fields:
          - label: 'NavLinks'
            name: 'navLinks'
            widget: list
            fields:
              - { label: 'Label', name: 'label', widget: 'string' }
              - { label: 'Href', name: 'href', widget: 'string' }
          - label: 'Testimonials'
            name: 'testimonials'
            widget: list
            fields:
              - { label: 'Quote', name: 'quote', widget: 'text' }
          - label: 'Projects'
            name: 'projects'
            widget: list
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'text' }
              - { label: 'Link', name: 'link', widget: 'string' }
              - { label: 'Image Source', name: 'imgSrc', widget: 'string' }
          - label: 'Services'
            name: 'services'
            widget: list
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'text' }
              - { label: 'Image Source', name: 'imgSrc', widget: 'string' }
