import Head from 'next/head';
import dynamic from 'next/dynamic';

import Navbar from '../components/Navbar/Navbar';
import Hero from '../containers/Hero/Hero';

const Contact = dynamic(() => import('../containers/Contact/Contact'));
const FAQ = dynamic(() => import('../containers/FAQ/FAQ'));
const Footer = dynamic(() => import('../containers/Footer/Footer'));
const Posts = dynamic(() => import('../containers/Posts/Posts'));
const Process = dynamic(() => import('../containers/Process/Process'));
const Projects = dynamic(() => import('../containers/Projects/Projects'));
const Services = dynamic(() => import('../containers/Services/Services'));
const Skills = dynamic(() => import('../containers/Skills/Skills'));
const Testimonials = dynamic(() =>
  import('../containers/Testimonials/Testimonials'),
);

export default function Home() {
  return (
    <>
      <Head>
        <title>Reda Alhourani | Application Development Consultant</title>
        {/* <meta name='description' content='Generated by create next app' /> */}
        <link rel='icon' href='/favicon.png' />
      </Head>
      <Navbar />
      <main>
        <Hero />
        <Projects />
        <Process />
        <Skills />
        <Services />
        <Testimonials />
        <Posts />
        <FAQ />
        <Contact />
      </main>
      <Footer />
    </>
  );
}
