import Head from 'next/head';
import Navbar from '../components/Navbar/Navbar';
import Contact from '../containers/Contact/Contact';
import FAQ from '../containers/FAQ/FAQ';
import Footer from '../containers/Footer/Footer';
import Hero from '../containers/Hero/Hero';
import Posts from '../containers/Posts/Posts';
import Process from '../containers/Process/Process';
import Projects from '../containers/Projects/Projects';
import Services from '../containers/Services/Services';
import Skills from '../containers/Skills/Skills';
import Testimonials from '../containers/Testimonials/Testimonials';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <main>
        <Hero />
        <Projects />
        <Process />
        <Skills />
        <Services />
        <Testimonials />
        <Posts />
        <FAQ />
        <Contact />
      </main>
      <Footer />
    </>
  );
}
